### PR TITLE
Added repo link of Assignment 2.2

### LINKED ISSUE #6: Assignment 2.2 ML Flow

### PR DESCRIPTION
**Pull request by pulkitsingh28**
closes #6

### CODE REVIEW

**Comment by pavana-priya2103** [comment]
where is the repo link? Can u please send me the repo link in the comments as I am unable to find one.

**Comment by pulkitsingh28** [comment]
It's in the readme file. https://github.com/pulkitsingh28/Ml-FLow

**Comment by pavana-priya2103** [comment]
Thank you for sending me the link, I can see that u r training the data, where are u testing it?

**Comment by pulkitsingh28** [comment]
I followed this video. https://www.youtube.com/watch?v=6z0_n8kxh-g
I have to complete the #2 of this assignment where I'll perform testing

**Pull request merged**
